project_name: cometbft-load-test

env:
  # Require use of Go modules.
  - GO111MODULE=on

builds:
  - main: ./cmd/cometbft-load-test/main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64

checksum:
  name_template: SHA256SUMS-{{.Version}}.txt
  algorithm: sha256

release:
  header: |
    See the CHANGELOG for details regarding this release.
  name_template: "v{{.Version}}"

archives:
  - files:
    - LICENSE
    - README.md
    - CHANGELOG.md
